version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    # ポートは公開せず内部ネットワークのみで待受
    expose:
      - "8000"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: always