version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm ci || npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/userpost/api
    depends_on:
      - web
