# Generated by Django 5.2.5 on 2025-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='content_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
