# Generated by Django 5.2.5 on 2025-10-18 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0002_alter_good_content_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='user_id',
            new_name='username_legacy',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='user_id',
            new_name='username_legacy',
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('username_legacy', 'content_url')},
        ),
        migrations.AddField(
            model_name='good',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
