# Generated by Django 5.2.5 on 2025-10-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlists', '0001_initial'),
        ('userpost', '0007_remove_good_good_user_content_unique_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userposts', to='userlists.userlist'),
        ),
    ]
