# Generated by Django 5.2.5 on 2025-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest_id',
            field=models.UUIDField(blank=True, help_text='ゲストユーザー識別用のUUID', null=True, unique=True, verbose_name='guest ID'),
        ),
    ]
