# Generated by Django 5.2.5 on 2025-10-23 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goot_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GootList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_goots', to=settings.AUTH_USER_MODEL)),
                ('userlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goots', to='userlists.userlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userlist',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_list_name'),
        ),
        migrations.AddConstraint(
            model_name='gootlist',
            constraint=models.UniqueConstraint(fields=('user', 'userlist'), name='uniq_user_list_goot'),
        ),
    ]
